function GetQuestion()
{
    var question= new Array(
        //"Hoe oud voel je je?",
        "Waar ben je trots op?",
        "Wie is je favoriete artiest en favoriete nummer van hun?",
        "Wat is succes voor jou?",
        //"Wat kan er niet missen in je droomhuis?",
        "Wat is je favoriete dier?",
        "Wat maakt voor jou een goeie vriendschap?",
        "Wat heb je dagelijks nodig?",
        //"Als je met 1 iemand een dag kon ruilen, met wie en waarom?",
        //"Wat is één ding wat je blij maakt?",
        "Waar wil je jezelf zien in 20 jaar?",
        // "Wie is de meest inspirerende persoon die je kent?",
        "Wat is jou beste kwaliteit?",
        "Met welke persoon ben je het meest close?",
        "Wat is jou favoriete moment van de dag?",
        "Wat is één ding waar je veel spijt van hebt?",
        // "Waar krijg je energie van?",
        "Wat is je favoriete boek?",
        "Welke superkracht zou je willen hebben?",
        "Als je een disneyprinces zou zijn, welke?",
        // "Wat is je favoriete YouTube kanaal?",
        "Als je het antwoord op elke vraag zou weten, welke vraag zou je stellen? (Geen zin van het leven)",
        "Als je een drankje zou zijn, wat zou je dan zijn?",
        "Als je voor altijd 1 leeftijd kon blijven, welke zou je dan zijn?",
        "Wat is het mooiste kado wat je ooit hebt gekregen?",
        "Wat is je favoriete dag van het jaar?",
        "Welke baan zou je nooit (weer) willen doen?",
        // "Wat motiveert jou?",
        //"Wat is het spannendste wat je ooit heb gedaan?",
        "Wat doe je het liefst?",
        "Wat is de beste baan die je ooit hebt gehad?",
        "Wat is je favoriete ijssmaak?",
        "Welke app gebruik je het meest?",
        //"Wat irriteert jou?",
        "Welk mythisch wezen zou je als huisdier willen hebben?",
        "Waarvoor kan ik je wakker maken?",
        // "Beschrijf je zelf in 1 woord",
        // "Als je 1 nummer voor de rest van je leven moest luisteren, welke?",
        "Als je 1 ding van de aarde kan verwijderen, wat zou dat zijn?",
        "Als je 1 artiest kan zijn tijdens een concert, welke zou je dan zijn?",
        //"Als je met een mede-student / collega kan ruilen voor 1 week, met wie zou je dan zijn en waarom?",
        // "Welk talent van je zou je laten zien op een talentenjacht?",
        // "Wat is een gedachte die je vroeger had maar nu niet meer?",
        "Wat is het eerste ding wat je denkt dat mensen aan je opmerken?",
        "Welk cijfer geef je jezelf van 1 tot 10?",
        // "Wat is het belangrijkste in je leven?",
        // "Waar ben jij bang voor?",
        "Wat denk je dat er is na de dood?",
        "Wat is een onzekerheid waar je uit bent gegroeid?",
        // "Waar wil je over 12 maanden zijn? / wat wil je bereikt hebben in die periode? (Mag iets kleins of iets groots zijn)",
        "Waar heb je op dit moment het meest moeite mee?",
        "Wat is iets wat je wilt dat meer mensen over je weten?",
        "Wat zou jij uit het verleden nu over jou denken?",
        // "Wat is een slechte eigenschap die je wilt wegwerken?",
        "Wat is een vraag die je jezelf veel stelt?",
        "Welk instrument zou je willen spelen?",
        "Wat is iets waar je naar uitkijkt? (Mag op dit moment zijn of later)",
        "Wat is iets wat andere mensen niet verwachten bij jou?",
        // "Wat is een moment in het verleden waar je vaak aan terug denkt?",
        "Waarin ben je het meest gegroeid het afgelopen jaar?",
        "Wat doe je het liefst als je alleen bent?",
        "Wat is iets wat je altijd kwijt raakt?",
        //"Wat is het laatste ding/gebeuren wat je goed liet voelen?",
        // "Wat is iets wat je verteld is, wat je nooit zal vergeten?",
        "Als je met 1 dier kan communiceren, welke zou dat dan zijn?",
        "Wat is het beste wat je is overkomen de afgelopen 12 maanden?",
        "Wat is het domste waar je ooit geld voor betaald?",
        // "Wat is je favoriete (oude) Nickelodeon serie?",
        //"Wat is je favoriete (oude) Disney XD serie?",
        // "Als geld geen probleem is, wat zou je nu dan gaan doen?",
        "Wat is iets kleins wat je gelukkig maakt?",
        "Wat was tot nu toe het beste jaar van je leven?",
        "Als je moest kiezen, welke sport zou je professioneel doen?",
        "Als je een dier uit de jungle zou zijn, welk geluid zou je maken?",
        "Wat is een assumptie die je van mij had die uiteindelijk niet waar bleek te zijn? Of juist wel?",
        "In welke fictieve wereld zou je willen wonen en waarom?",
        // "Als je met 1 iemand 1 uur kon praten, wie zou je dan kiezen en waarom?"
        );
    var random = question[Math.floor(Math.random() * question.length)];
    document.getElementById("question").innerHTML=random;
    var element = document.getElementById("questionBtn");
    element.remove();
}

function GetRefresh(){
    window.location.reload();
}